from google.colab import drive
drive.mount("/content/drive")
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('tested.csv')
print("Dataset Info:")
print(df.info())
print("\nSummary Statistics:")
print(df.describe())
print("\nMissing Values:")
print(df.isnull().sum())
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df.dropna(subset=['Fare'], inplace=True)  # if Fare has any nulls
print("\nSex Distribution:\n", df['Sex'].value_counts())
print("\nPclass Distribution:\n", df['Pclass'].value_counts())
print("\nEmbarked Distribution:\n", df['Embarked'].value_counts())
sns.countplot(x='Survived', data=df)
plt.title('Survival Counts')
plt.show()
sns.barplot(x='Sex', y='Survived', data=df)
plt.title('Survival Rate by Gender')
plt.show()
sns.histplot(df['Age'], bins=30, kde=True)
plt.title('Age Distribution')
plt.show()
sns.boxplot(x='Survived', y='Age', data=df)
plt.title('Age vs Survival (Boxplot)')
plt.show()
sns.barplot(x='Pclass', y='Survived', data=df)
plt.title('Survival Rate by Passenger Class')
plt.show()
sns.swarmplot(x='Survived', y='Age', data=df)
plt.title('Swarmplot: Age vs Survival')
plt.show()
plt.figure(figsize=(8,6))
numeric_df = df.select_dtypes(include=np.number)
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
print("\nFamilySize Feature:\n", df[['SibSp', 'Parch', 'FamilySize']].head())
sns.barplot(x='FamilySize', y='Survived', data=df)
plt.title('Survival Rate by Family Size')
plt.show()
