# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1liPgePRMqAoByJmtq_giXthFhhnyiETu
"""

# 1. Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 2. Load Dataset
df = pd.read_csv("train.csv")

# 3. Basic Info
print("Dataset Info:")
print(df.info())

print("\nSummary Statistics:")
print(df.describe())

print("\nMissing Values:")
print(df.isnull().sum())

# 4. Handle Missing Values
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df['Cabin'].fillna('Unknown', inplace=True)

# 5. Remove Duplicates (if any)
df.drop_duplicates(inplace=True)

# 6. Convert Data Types if needed
# (no conversion needed for Titanic dataset columns)

# 7. Univariate Analysis
plt.figure(figsize=(10, 5))
sns.histplot(df['Age'], bins=30, kde=True)
plt.title("Age Distribution")
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(x='Survived', data=df)
plt.title("Survival Count")
plt.xticks([0, 1], ['No', 'Yes'])
plt.show()

# 8. Box Plot: Age by Pclass
plt.figure(figsize=(8, 5))
sns.boxplot(x='Pclass', y='Age', data=df)
plt.title("Age Distribution by Passenger Class")
plt.show()

# 9. Count Plot: Gender
sns.countplot(x='Sex', data=df, hue='Survived')
plt.title("Survival by Gender")
plt.legend(['Not Survived', 'Survived'])
plt.show()

# 10. Correlation Heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# 11. Pair Plot
sns.pairplot(df[['Age', 'Fare', 'Pclass', 'Survived']])
plt.suptitle("Pairwise Plots", y=1.02)
plt.show()

# 12. Violin Plot
plt.figure(figsize=(8, 5))
sns.violinplot(x='Pclass', y='Age', hue='Survived', data=df, split=True)
plt.title("Violin Plot: Age by Pclass and Survival")
plt.show()

# 13. Feature Engineering
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
print("\nCreated Feature: FamilySize")

# 14. GroupBy Insights
print("\nSurvival Rate by Gender:")
print(df.groupby('Sex')['Survived'].mean())

print("\nSurvival Rate by Pclass:")
print(df.groupby('Pclass')['Survived'].mean())

print("\nSurvival Rate by FamilySize:")
print(df.groupby('FamilySize')['Survived'].mean())

"""## Top 5 Insights from EDA

1. **Females had a much higher survival rate** compared to males.
2. **Passengers in 1st class** had higher chances of survival.
3. **Passengers with family size 2 to 4** survived more compared to solo or large families.
4. **Age and survival have a weak but visible trend** — children had better survival.
5. **Fare and Pclass are positively correlated with survival**, suggesting wealth was a survival advantage.

"""